spring:
  datasource:
    url: jdbc:mysql://localhost:3306/user-service?useSSL=false&serverTimezone=Europe/Warsaw
    driverClassName: com.mysql.cj.jdbc.Driver
    username: user
    password: password
  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    show-sql: true
    hibernate:
      ddl-auto: create-drop