spring:
  datasource:
    url: jdbc:mysql://localhost:3306/users?useSSL=false&serverTimezone=Europe/Warsaw
    driverClassName: com.mysql.cj.jdbc.Driver
    username: uzytkownik
    password: uzytkownik
  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    show-sql: true
    hibernate:
      ddl-auto: create-drop